### ISSUE TITLE
How do I find out what orders belong to a user?

### ISSUE THREAD

**Issue by dhilowitz** [corcel/woocommerce#10]
It would be great to have some basic documentation for this plugin. I'm looking for answers to the following questions:
- Given a user ID, how do I find out what orders belong to them?
- Given a user ID, how do I find out which products they have purchased?
- Given a product, how do I find out whether or not a user has purchased said product?

**Comment by Dartui** [comment]
> Given a user ID, how do I find out what orders belong to them:

```php
use Corcel\WooCommerce\Model\Order;

Order::hasMeta('_customer_user', 1)->get(); // 1 - customer ID
```

> Given a user ID, how do I find out which products they have purchased

```php
use Corcel\WooCommerce\Model\Order;

// get orders and eager load items with product to optimize queries count
$orders   = Order::with('items.product')->hasMeta('_customer_user', 1)->get();
$items    = $orders->pluck('items')->flatten(1); // all items from orders
$products = $items->pluck('product');            // all products from all orders (non-unique)
```

Unfortunately relation from product to orders is not yet implemented, so your third question cannot be solved right now. PRs are welcome.

**Comment by dhilowitz** [comment]
Thanks! This is already very helpful. :)

**Comment by Dartui** [comment]
> Given a product, how do I find out whether or not a user has purchased said product:

With the last commit from master you can do it for example in this way:

```php
$product = Product::find(1);
$orders  = $product->items->pluck('order');
$orders  = $orders->filter(function ($order) {
    return $order->hasMeta('_customer_id', 1);
});
```

I will close this issue. Any work with documentation will be continued in this issue: #11
