### ISSUE TITLE
Could not parse '1604067041'

### ISSUE THREAD

**Issue by daniellaurel** [corcel/woocommerce#18]
Im using Laravel 8.3 and Corcel 5.0

When I trying to return a order from a specific customer it returns 
**"message": "Could not parse '1604067041': DateTime::__construct(): Failed to parse time string (1604067041) at position 7 (0): Unexpected character",**

here is my code on my controller 
$customer = Customer::find(6);
$customerOrders = $customer->orders;
return response()->json($customerOrders);

Am I doing it wrong?

**Comment by Dartui** [comment]
WooCommerce stores completed and paid date in two versions - datetime and timestamp:

![obraz](https://user-images.githubusercontent.com/2657856/97725819-e2778180-1ace-11eb-9ce5-5f22e64cfe9d.png)

By mistake I took timestamp version of date and Carbon is throwing error while creating its instance from it.

https://github.com/corcel/woocommerce/blob/99b931149874ecef3110127b2a4d402cd1f07be0/src/Model/Order.php#L144-L149

I will prepare fix for that in a minutes. Thanks for reporting!

**Comment by Dartui** [comment]
Could you check if changes from `issue-18` branch fixes this error? You can test it by by requiring it in this way:

```sh
composer require corcel/woocommerce:dev-issue-18
```

**Comment by daniellaurel** [comment]
> Could you check if changes from `issue-18` branch fixes this error? You can test it by by requiring it in this way:
> 
> ```shell
> composer require corcel/woocommerce:dev-issue-18
> ```

It is working now. Thank you so much

**Comment by Dartui** [comment]
New version of package has been released. Thanks again for reporting!
