### ISSUE TITLE
exception while saving Meta Data

### ISSUE THREAD

**Issue by Rahulyadav97** [corcel/woocommerce#24]
whenever I am creating/updating any meta data with 

$order:find(1)
$order->saveField($field,$value);

It is  Throwing Exception with Error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'po_number' in 'field list' (SQL: update `wp_posts` set `post_modified_gmt` = 2021-06-24 12:28:16, `po_number` = trweerter, `wp_posts`.`post_modified` = 2021-06-24 12:28:16 where `ID` = 5410);

I think it is because it is trying to update order dates in WP_POST with that field value also.

**Comment by Dartui** [comment]
Hello!

Are you sure that this method is generating error? `saveField` calls `meta` relation in model, so it should not try to modify `wp_posts` table:

https://github.com/corcel/corcel/blob/c3ff0312ef21f7be38c2351c37dc7a296fe5d0f3/src/Concerns/MetaFields.php#L123-L126

Could you please submit part of code from you application which generates this error?

**Comment by Rahulyadav97** [comment]
it was bcz  i save method call in my code which was call 
$order->filedname  = $value;
$order->save() ;

thanks for your prompt response. 
I am using this library with zf3.

**Comment by Rahulyadav97** [comment]
can you suggest me best function to delete a post like product or order with deleting all records associated with this, like meta data

**Comment by Dartui** [comment]
I have no idea how this package works with ZF3. In Laravel application you could make something like this:

```php
$product = Product::find(1);
$product->meta()->delete();
```

This part of code will delete all product meta. To create e.g. product, take a look on this comment: https://github.com/corcel/woocommerce/issues/7#issuecomment-703116173. Creating order works in similar way.

I will close this issue for now, if you have any more question feel free to write here.
