### ISSUE TITLE
Filter products by category

### ISSUE THREAD

**Issue by italo1983** [corcel/woocommerce#32]
Hello,
i need to fillter products by category, how can I do?
I did not find anything in the documentation.

**Comment by Dartui** [comment]
Between products and categories is basic `BelongsToMany` Laravel relation:

https://github.com/corcel/woocommerce/blob/b0af08471c34de655f3d0b185a14f113351ef6a0/src/Model/Product.php#L395-L403

So you can use relation queries: https://laravel.com/docs/9.x/eloquent-relationships#querying-relationship-existence

I wrote this code from memory so probably it will not work, you need to adjust it:

```php
$products = Product::whereHas('categories', function($query) {
    $query->whereHas('terms', function($query) {
        $query->where('slug', '=', 'category_slug');
    })
})->get();
```
