### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by dangnhdev** [corcel/woocommerce#40]
Hello, [corcel/corcel](https://github.com/corcel/corcel) now support Laravel 11 in version 8.0. Can you fix dependency to support laravel 11 too?

**Comment by twmbx** [comment]
#37

**Comment by Dartui** [comment]
Hi, thanks for raising this issue. I will try my best to upgrade the package and testsuite for latest Laravel version in current week. Thanks for your patience

**Comment by Dartui** [comment]
Resolved in #37
