### ISSUE TITLE
OrderBuilder not found

### ISSUE THREAD

**Issue by overwise** [corcel/woocommerce#6]
Getting this error:
`Class 'Corcel\WooCommerce\Builder\OrderBuilder' not found`

I believe the reason is that OrderBuilder is actually:
`Corcel\WooCommerce\Model\Builder\OrderBuilder`
and Order tries to use it as:
`Corcel\WooCommerce\Builder\OrderBuilder`

**Comment by overwise** [comment]
AddressesTrait tries to use
`Corcel\WooCommerce\Address`
as
`Corcel\WooCommerce\Classes\Address`

**Comment by RiaanZA** [comment]
Also
`use Corcel\WooCommerce\Classes\Payment`;
should be
`use Corcel\WooCommerce\Payment;`
