### ISSUE TITLE
Not Compatible with corcel 4.0, 

### ISSUE THREAD

**Issue by shigristudy** [corcel/woocommerce#8]
i'm trying to install both corcel and corcel/woocommerce but its showing dependency error.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for corcel/woocommerce dev-master -> satisfiable by corcel/woocommerce[dev-master].
    - Conclusion: remove jgrossi/corcel v4.0.0
    - Conclusion: don't install jgrossi/corcel v4.0.0
    - corcel/woocommerce dev-master requires jgrossi/corcel ~2.4 -> satisfiable by jgrossi/corcel[2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev].    - Can only install one of: jgrossi/corcel[2.4.x-dev, v4.0.0].
PS C:\xampp\htdocs\fundamal_reporting> composer require corcel/woocommerce
Using version dev-master for corcel/woocommerce

**Comment by ajgentile** [comment]
The source code will still work, but you'll have to set up the files manually. Go into the src of this repo and put those files directly in your project. References to the Corcel namespace should still work fine. You'll have to update the namespaces to your own project, but everything should work properly.
