### ISSUE TITLE
Is this done now? 

### ISSUE THREAD

**Issue by Stevemoretz** [corcel/woocommerce#9]
Hi thanks for this the last commit seems to be years ago, is it done or what?

**Comment by Dartui** [comment]
Fixed in 0a65134

**Comment by Stevemoretz** [comment]
Thanks man so now all the features are implemented?

Why not having a readme.md?

I'd love to read your full readme

**Comment by Dartui** [comment]
Not all, but the most basic - yes. Feel free to send PR if you find something missing.

In a couple of days I will prepare readme, tag version and make release.
